"""API 形状参考,不是实现代码。"""
from contextvars import ContextVar
from typing import Optional

# 三个 ContextVar,默认 None
_task_id_var: ContextVar[Optional[str]] = ContextVar("task_id", default=None)
_thread_id_var: ContextVar[Optional[str]] = ContextVar("thread_id", default=None)
_request_id_var: ContextVar[Optional[str]] = ContextVar("request_id", default=None)


def bind_task_id(task_id: str, thread_id: str | None = None) -> None: ...
def clear_task_id() -> None: ...
def bind_request_id(request_id: str) -> None: ...
def clear_request_id() -> None: ...
def get_request_id() -> str | None: ...
def get_task_id() -> str | None: ...
